export const paths = {
  home: '/',
  landing: '/',
  dashboard: '/dashboard',
  customers: '/customers',
  invoices: '/invoices',
  invoiceNew: '/invoices/new',
  invoiceDetail: (id: string) => `/invoices/${id}`,
  invoiceEdit: (id: string) => `/invoices/${id}/edit`,
  reports: '/app/reports',
  receipts: '/receipts',
  settings: '/settings',
  onboarding: '/onboarding',
  authCallback: '/auth/callback',
  admin: '/admin',
  adminCompanies: '/admin/companies',
  adminUsers: '/admin/users',
  companyDisabled: '/company-disabled',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  blog: '/blog',
  blogCategory: (slug: string) => `/blog/category/${slug}`,
  article: (slug: string) => `/article/${slug}`,
  tools: '/tools',
} as const

export type AppPath = string
