import {
  addExportTitle,
  autofitColumns,
  createWorkbook,
  currencyFormat,
  dateFormat,
  dateTimeFormat,
  downloadWorkbook,
  stampWorkbook,
  styleHeaderRow,
  thinBorder,
} from '@/lib/excel'
import {
  fetchCustomersForExport,
  fetchInvoicesForExport,
  fetchSalesForExport,
} from '@/services/exports/api'
import { APP_NAME } from '@/utils'

function fileStamp() {
  const now = new Date()
  const yyyy = now.getFullYear()
  const mm = String(now.getMonth() + 1).padStart(2, '0')
  const dd = String(now.getDate()).padStart(2, '0')
  return `${yyyy}-${mm}-${dd}`
}

function parseDate(value: string | null | undefined) {
  if (!value) return null
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? null : date
}

export async function exportCustomersExcel() {
  const customers = await fetchCustomersForExport()
  const workbook = await createWorkbook()
  stampWorkbook(workbook, `${APP_NAME} Customers`)

  const sheet = workbook.addWorksheet('Customers', {
    views: [{ state: 'frozen', ySplit: 3 }],
  })

  const headers = [
    'Name',
    'Email',
    'Phone',
    'Address',
    'Notes',
    'Created At',
    'Updated At',
  ]

  addExportTitle(
    sheet,
    'Customers Export',
    `Generated by ${APP_NAME} · ${customers.length} record(s) · ${fileStamp()}`,
    headers.length,
  )

  const headerRowIndex = 3
  sheet.getRow(headerRowIndex).values = [undefined, ...headers]
  styleHeaderRow(sheet, headerRowIndex, headers.length)

  customers.forEach((customer, index) => {
    const row = sheet.getRow(headerRowIndex + 1 + index)
    row.values = [
      undefined,
      customer.name,
      customer.email ?? '',
      customer.phone ?? '',
      customer.address_line1 ?? '',
      customer.notes ?? '',
      parseDate(customer.created_at),
      parseDate(customer.updated_at),
    ]

    row.eachCell({ includeEmpty: false }, (cell, colNumber) => {
      cell.border = thinBorder
      cell.font = { name: 'Calibri', size: 11 }
      cell.alignment = { vertical: 'middle', wrapText: true }
      if (colNumber === 6 || colNumber === 7) {
        cell.numFmt = dateTimeFormat
      }
    })
  })

  autofitColumns(sheet)
  await downloadWorkbook(workbook, `${APP_NAME}-customers-${fileStamp()}.xlsx`)
  return customers.length
}

export async function exportInvoicesExcel() {
  const invoices = await fetchInvoicesForExport()
  const workbook = await createWorkbook()
  stampWorkbook(workbook, `${APP_NAME} Invoices`)

  const sheet = workbook.addWorksheet('Invoices', {
    views: [{ state: 'frozen', ySplit: 3 }],
  })

  const headers = [
    'Invoice Number',
    'Customer',
    'Customer Email',
    'Status',
    'Issue Date',
    'Due Date',
    'Currency',
    'Subtotal',
    'Discount',
    'Tax Rate (%)',
    'Tax Amount',
    'Total',
    'Created At',
  ]

  addExportTitle(
    sheet,
    'Invoices Export',
    `Generated by ${APP_NAME} · ${invoices.length} record(s) · ${fileStamp()}`,
    headers.length,
  )

  const headerRowIndex = 3
  sheet.getRow(headerRowIndex).values = [undefined, ...headers]
  styleHeaderRow(sheet, headerRowIndex, headers.length)

  invoices.forEach((invoice, index) => {
    const row = sheet.getRow(headerRowIndex + 1 + index)
    row.values = [
      undefined,
      invoice.invoice_number,
      invoice.customer?.name ?? '',
      invoice.customer?.email ?? '',
      invoice.status,
      parseDate(invoice.issue_date),
      parseDate(invoice.due_date),
      invoice.currency,
      invoice.subtotal,
      invoice.discount_amount,
      invoice.tax_rate,
      invoice.tax_amount,
      invoice.total,
      parseDate(invoice.created_at),
    ]

    row.eachCell({ includeEmpty: false }, (cell, colNumber) => {
      cell.border = thinBorder
      cell.font = { name: 'Calibri', size: 11 }
      cell.alignment = { vertical: 'middle' }

      if (colNumber === 5 || colNumber === 6 || colNumber === 13) {
        cell.numFmt = colNumber === 13 ? dateTimeFormat : dateFormat
      }
      if ([8, 9, 11, 12].includes(colNumber)) {
        cell.numFmt = currencyFormat
        cell.alignment = { vertical: 'middle', horizontal: 'right' }
      }
      if (colNumber === 10) {
        cell.numFmt = '0.00'
        cell.alignment = { vertical: 'middle', horizontal: 'right' }
      }
    })
  })

  // Totals row
  if (invoices.length > 0) {
    const totalsRowIndex = headerRowIndex + 1 + invoices.length
    const totalsRow = sheet.getRow(totalsRowIndex)
    const firstDataRow = headerRowIndex + 1
    const lastDataRow = totalsRowIndex - 1

    totalsRow.getCell(1).value = 'TOTALS'
    totalsRow.getCell(1).font = { bold: true, name: 'Calibri', size: 11 }
    totalsRow.getCell(8).value = {
      formula: `SUM(H${firstDataRow}:H${lastDataRow})`,
    }
    totalsRow.getCell(9).value = {
      formula: `SUM(I${firstDataRow}:I${lastDataRow})`,
    }
    totalsRow.getCell(11).value = {
      formula: `SUM(K${firstDataRow}:K${lastDataRow})`,
    }
    totalsRow.getCell(12).value = {
      formula: `SUM(L${firstDataRow}:L${lastDataRow})`,
    }

    ;[8, 9, 11, 12].forEach((col) => {
      const cell = totalsRow.getCell(col)
      cell.numFmt = currencyFormat
      cell.font = { bold: true, name: 'Calibri', size: 11 }
      cell.border = thinBorder
    })
  }

  autofitColumns(sheet)
  await downloadWorkbook(workbook, `${APP_NAME}-invoices-${fileStamp()}.xlsx`)
  return invoices.length
}

export async function exportSalesExcel() {
  const sales = await fetchSalesForExport()
  const workbook = await createWorkbook()
  stampWorkbook(workbook, `${APP_NAME} Sales`)

  const sheet = workbook.addWorksheet('Sales', {
    views: [{ state: 'frozen', ySplit: 3 }],
  })

  const headers = [
    'Invoice Number',
    'Customer',
    'Customer Email',
    'Issue Date',
    'Paid At',
    'Currency',
    'Subtotal',
    'Discount',
    'GST Rate (%)',
    'GST Amount',
    'Grand Total',
    'Status',
  ]

  addExportTitle(
    sheet,
    'Sales Export',
    `Paid invoices only · Generated by ${APP_NAME} · ${sales.length} sale(s) · ${fileStamp()}`,
    headers.length,
  )

  const headerRowIndex = 3
  sheet.getRow(headerRowIndex).values = [undefined, ...headers]
  styleHeaderRow(sheet, headerRowIndex, headers.length)

  sales.forEach((sale, index) => {
    const row = sheet.getRow(headerRowIndex + 1 + index)
    row.values = [
      undefined,
      sale.invoice_number,
      sale.customer_name,
      sale.customer_email,
      parseDate(sale.issue_date),
      parseDate(sale.paid_at),
      sale.currency,
      sale.subtotal,
      sale.discount_amount,
      sale.tax_rate,
      sale.tax_amount,
      sale.total,
      sale.status,
    ]

    row.eachCell({ includeEmpty: false }, (cell, colNumber) => {
      cell.border = thinBorder
      cell.font = { name: 'Calibri', size: 11 }
      cell.alignment = { vertical: 'middle' }

      if (colNumber === 4) cell.numFmt = dateFormat
      if (colNumber === 5) cell.numFmt = dateTimeFormat
      if ([7, 8, 10, 11].includes(colNumber)) {
        cell.numFmt = currencyFormat
        cell.alignment = { vertical: 'middle', horizontal: 'right' }
      }
      if (colNumber === 9) {
        cell.numFmt = '0.00'
        cell.alignment = { vertical: 'middle', horizontal: 'right' }
      }
    })
  })

  if (sales.length > 0) {
    const totalsRowIndex = headerRowIndex + 1 + sales.length
    const totalsRow = sheet.getRow(totalsRowIndex)
    const firstDataRow = headerRowIndex + 1
    const lastDataRow = totalsRowIndex - 1

    totalsRow.getCell(1).value = 'TOTAL REVENUE'
    totalsRow.getCell(1).font = { bold: true, name: 'Calibri', size: 11 }
    totalsRow.getCell(7).value = {
      formula: `SUM(G${firstDataRow}:G${lastDataRow})`,
    }
    totalsRow.getCell(8).value = {
      formula: `SUM(H${firstDataRow}:H${lastDataRow})`,
    }
    totalsRow.getCell(10).value = {
      formula: `SUM(J${firstDataRow}:J${lastDataRow})`,
    }
    totalsRow.getCell(11).value = {
      formula: `SUM(K${firstDataRow}:K${lastDataRow})`,
    }

    ;[7, 8, 10, 11].forEach((col) => {
      const cell = totalsRow.getCell(col)
      cell.numFmt = currencyFormat
      cell.font = { bold: true, name: 'Calibri', size: 11 }
      cell.border = thinBorder
    })
  }

  autofitColumns(sheet)
  await downloadWorkbook(workbook, `${APP_NAME}-sales-${fileStamp()}.xlsx`)
  return sales.length
}
