/**
 * Generates public/sitemap.xml, public/sitemap-index.xml, and refreshes robots.txt.
 * Source of truth: public route meta (run generate:route-meta first if content changed).
 *
 * Usage: node scripts/generate-sitemap.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SITE = 'https://receiptflow.velonerp.com'
const TODAY = new Date().toISOString().slice(0, 10)
const root = process.cwd()

function extractPathsFromRouteMeta() {
  const src = readFileSync(
    join(root, 'src/content/public-route-meta.ts'),
    'utf8',
  )
  const paths = new Set(['/'])
  for (const match of src.matchAll(/"path":\s*"([^"]+)"/g)) {
    paths.add(match[1])
  }
  for (const match of src.matchAll(/path:\s*'([^']+)'/g)) {
    paths.add(match[1])
  }
  return [...paths].sort((a, b) => {
    if (a === '/') return -1
    if (b === '/') return 1
    return a.localeCompare(b)
  })
}

function priorityFor(path) {
  if (path === '/') return '1.0'
  if (path === '/pricing') return '0.95'
  if (
    path === '/features' ||
    path === '/comparisons' ||
    path === '/blog' ||
    path === '/tools'
  ) {
    return '0.9'
  }
  if (path.startsWith('/article/')) return '0.75'
  if (path.startsWith('/blog/')) return '0.7'
  if (path.startsWith('/receiptflow-vs-')) return '0.85'
  if (
    path.includes('billing-software') ||
    path.includes('invoice') ||
    path.includes('gst')
  ) {
    return '0.85'
  }
  return '0.8'
}

function changefreqFor(path) {
  if (path === '/') return 'weekly'
  if (path === '/blog' || path.startsWith('/article/')) return 'weekly'
  if (path === '/pricing') return 'weekly'
  return 'monthly'
}

function escapeXml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

const paths = extractPathsFromRouteMeta()

const urlEntries = paths
  .map(
    (path) => `  <url>
    <loc>${escapeXml(`${SITE}${path === '/' ? '/' : path}`)}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${changefreqFor(path)}</changefreq>
    <priority>${priorityFor(path)}</priority>
  </url>`,
  )
  .join('\n')

const sitemapPages = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`

/** Primary page sitemap for crawlers. */
writeFileSync(join(root, 'public/sitemap.xml'), sitemapPages)

const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>${SITE}/sitemap.xml</loc>
    <lastmod>${TODAY}</lastmod>
  </sitemap>
  <sitemap>
    <loc>${SITE}/sitemap-images.xml</loc>
    <lastmod>${TODAY}</lastmod>
  </sitemap>
</sitemapindex>
`

writeFileSync(join(root, 'public/sitemap-index.xml'), sitemapIndex)

const robots = `# ReceiptFlow — ${SITE}
# Generated by scripts/generate-sitemap.mjs — regenerate with: npm run sitemap

User-agent: *
Allow: /

# Private app surfaces (authenticated)
Disallow: /dashboard
Disallow: /customers
Disallow: /invoices
Disallow: /app/
Disallow: /settings
Disallow: /admin
Disallow: /onboarding
Disallow: /company-disabled
Disallow: /auth/

# Auth flows
Disallow: /login
Disallow: /register
Disallow: /forgot-password
Disallow: /reset-password

# Legacy / redirected paths (keep out of crawl budget)
Disallow: /home
Disallow: /receipts
Disallow: /signin
Disallow: /signup

# Sitemaps
Sitemap: ${SITE}/sitemap-index.xml
Sitemap: ${SITE}/sitemap.xml
Sitemap: ${SITE}/sitemap-images.xml
`

writeFileSync(join(root, 'public/robots.txt'), robots)

console.log('sitemap generated', {
  pages: paths.length,
  files: [
    'public/sitemap.xml',
    'public/sitemap-index.xml',
    'public/robots.txt',
  ],
})
